import { Skin } from '../types';
import { buildSkin, SkinSpec } from './skins';
import { MATERIALS } from './patina';
import { CLASSIC } from './theme';

/**
 * The skin catalogue.
 *
 * Ordered roughly by when you meet them. Levels are spaced against the
 * rebalanced XP curve (level 30 at about a year of steady play, 40 at two,
 * 59 at five), so there is always a next one visible without any of them
 * arriving so fast that it stops meaning anything.
 *
 * Three ways in, deliberately different in character:
 *   - LEVEL rewards accumulated effort, and is the steady drip.
 *   - FEAT rewards a specific story: the thing you dodged for half a year,
 *     the streak you rebuilt after a relapse.
 *   - SENIORITY rewards nothing but having stayed. It cannot be bought,
 *     rushed or farmed, only outlived — which is exactly why those skins are
 *     the ones that visibly age with the account.
 */

const SPECS: SkinSpec[] = [
  // ---------------------------------------------------------------- default
  {
    id: 'classic',
    name: 'Tavern',
    blurb: 'Where it started. Oak, candlelight and a hard shadow.',
    rarity: 'common',
    unlock: { kind: 'default' },
    canvas: CLASSIC.canvas,
    surface: CLASSIC.surface,
    frame: CLASSIC.frame,
    accent: CLASSIC.accent,
    ink: CLASSIC.ink,
    tokens: { ...CLASSIC },
  },

  // ------------------------------------------------------- the early ladder
  {
    id: 'moss',
    name: 'Deep Moss',
    blurb: 'A forest floor after rain.',
    rarity: 'common',
    unlock: { kind: 'level', level: 3 },
    canvas: '#1b241d',
    surface: '#2e3d31',
    frame: '#5a7a5f',
    accent: '#9ed36f',
    ink: '#e4efdc',
    good: '#3f8f52',
    miss: '#8a5a24',
  },
  {
    id: 'dusk',
    name: 'Dusk Harbour',
    blurb: 'The blue hour, just before the lamps come on.',
    rarity: 'common',
    unlock: { kind: 'level', level: 5 },
    canvas: '#17202e',
    surface: '#243349',
    frame: '#4a6a94',
    accent: '#ffb35c',
    ink: '#e2ebf7',
    good: '#2f8a6b',
    miss: '#a05a2c',
    info: '#7fd4e8',
  },
  {
    id: 'ember',
    name: 'Ember',
    blurb: 'Banked coals that refuse to go out.',
    rarity: 'common',
    unlock: { kind: 'level', level: 8 },
    canvas: '#241416',
    surface: '#3a1f21',
    frame: '#8a4038',
    accent: '#ff8a4c',
    ink: '#f7e2da',
    good: '#4f8f5a',
    danger: '#b02a2a',
  },
  {
    id: 'slate',
    name: 'Slate',
    blurb: 'Quiet, grey, and impossible to argue with.',
    rarity: 'common',
    unlock: { kind: 'level', level: 11 },
    canvas: '#1c1e21',
    surface: '#2b2e33',
    frame: '#5a6069',
    accent: '#9fb4c9',
    ink: '#e6e9ed',
    good: '#4a8f6d',
    xp: '#b9a6e6',
    material: MATERIALS.stone,
  },
  {
    id: 'parchment',
    name: 'Parchment',
    blurb: 'Ink on old paper. The first light skin.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 14 },
    canvas: '#e8dfc8',
    surface: '#f3ecd9',
    frame: '#a08a5f',
    accent: '#9c5b1f',
    ink: '#3a2f22',
    good: '#3f6b35',
    miss: '#9a5a1e',
    danger: '#8f2a24',
    warn: '#8a5a12',
    xp: '#6a3fa0',
    info: '#1f6b7a',
    title: '#7a3f14',
    material: MATERIALS.paper,
  },
  {
    id: 'orchid',
    name: 'Orchid Court',
    blurb: 'Purple velvet and brass fittings.',
    rarity: 'common',
    unlock: { kind: 'level', level: 17 },
    canvas: '#1e1729',
    surface: '#2e2340',
    frame: '#6a4f9a',
    accent: '#e0b0ff',
    ink: '#ece3f7',
    good: '#3f8f78',
    xp: '#ffd6a5',
    material: MATERIALS.cloth,
  },
  {
    id: 'rust',
    name: 'Rust & Bone',
    blurb: 'Weathered iron. Still holding.',
    rarity: 'common',
    unlock: { kind: 'level', level: 20 },
    canvas: '#221c19',
    surface: '#382c26',
    frame: '#8a5a3a',
    accent: '#d9a066',
    ink: '#efe3d6',
    good: '#5a8a4a',
  },
  {
    id: 'tide',
    name: 'Tidepool',
    blurb: 'Cold water over green stone.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 24 },
    canvas: '#101f24',
    surface: '#1b3038',
    frame: '#3f6f7a',
    accent: '#6fe0c8',
    ink: '#dceff2',
    good: '#2f9a7a',
    miss: '#96622a',
    info: '#8fd8ff',
    material: MATERIALS.glass,
  },
  {
    id: 'sakura',
    name: 'Sakura Dusk',
    blurb: 'Petals against a darkening sky.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 28 },
    canvas: '#241a22',
    surface: '#3a2a33',
    frame: '#9a5f77',
    accent: '#ffa8c5',
    ink: '#f7e4ec',
    good: '#5a9a72',
    xp: '#c9a8ff',
    material: MATERIALS.cloth,
  },
  {
    id: 'gilded',
    name: 'Gilded',
    blurb: 'A year of showing up, in gold leaf.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 32 },
    canvas: '#191510',
    surface: '#2a2318',
    frame: '#b8912f',
    accent: '#ffd76a',
    ink: '#f7efd9',
    good: '#4f8f52',
    title: '#ffc94a',
    material: MATERIALS.metal,
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    blurb: 'Volcanic glass. Nothing decorative left.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 40 },
    canvas: '#0d0d10',
    surface: '#191920',
    frame: '#3a3a48',
    accent: '#00e5b0',
    ink: '#e8e8f0',
    good: '#00b389',
    danger: '#e0344a',
    xp: '#9d7bff',
    info: '#4fd6ff',
    material: MATERIALS.glass,
  },
  {
    id: 'aurora',
    name: 'Aurora',
    blurb: 'Two years of nights, and the sky finally answered.',
    rarity: 'legend',
    unlock: { kind: 'level', level: 50 },
    canvas: '#0b1220',
    surface: '#14203a',
    frame: '#3f6fa8',
    accent: '#7effc8',
    ink: '#e6f0ff',
    good: '#2fc79a',
    miss: '#b06a2a',
    xp: '#b48cff',
    info: '#6fe0ff',
    title: '#a8ffe0',
    material: MATERIALS.crt,
  },

  // -------------------------------------------------------------- the feats
  {
    id: 'first-light',
    name: 'First Light',
    blurb: 'For the very first thing you ticked off.',
    rarity: 'common',
    unlock: { kind: 'feat', featId: 'first-blood' },
    canvas: '#20191f',
    surface: '#332633',
    frame: '#7a5a7a',
    accent: '#ffc9a8',
    ink: '#f2e6ee',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    blurb: 'A hundred days on one habit. Bronze and blood.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'century' },
    canvas: '#1d1613',
    surface: '#31241d',
    frame: '#a86f3a',
    accent: '#ff9f45',
    ink: '#f5e6d5',
    good: '#5f8f45',
    danger: '#a82e26',
    title: '#ffb45c',
  },
  {
    id: 'excavator',
    name: 'Excavator',
    blurb: 'You dug out something buried for half a year.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'excavation' },
    canvas: '#1a1a14',
    surface: '#2b2b1f',
    frame: '#7a7a4a',
    accent: '#d9d96a',
    ink: '#eeeedd',
    good: '#6a9a4a',
    miss: '#8a6a2a',
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    blurb: 'You slipped, and built it back higher.',
    rarity: 'legend',
    unlock: { kind: 'feat', featId: 'phoenix' },
    canvas: '#1c1013',
    surface: '#331a1c',
    frame: '#b04a3a',
    accent: '#ffb347',
    ink: '#ffeadf',
    good: '#5f9a5a',
    danger: '#d4402e',
    title: '#ff7a3c',
  },
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    blurb: 'An empty board. Rarer than any streak.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'clean-slate' },
    canvas: '#f2f2ef',
    surface: '#ffffff',
    frame: '#8f9a96',
    accent: '#1f7a68',
    ink: '#22282a',
    good: '#2f7a4f',
    miss: '#9a5a1e',
    danger: '#8f2a24',
    warn: '#8a5a12',
    xp: '#5a3fa0',
    info: '#1f6b8a',
    title: '#1f7a68',
  },
  {
    id: 'ironclad',
    name: 'Ironclad',
    blurb: 'A month without a single miss.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'unbroken-month' },
    canvas: '#15181c',
    surface: '#222830',
    frame: '#5f7285',
    accent: '#c8d8e8',
    ink: '#eef3f8',
    good: '#3f8f7a',
    xp: '#a8b8ff',
    material: MATERIALS.metal,
  },
  {
    id: 'archivist',
    name: 'Archivist',
    blurb: 'Ten long-buried jobs, all finished.',
    rarity: 'rare',
    unlock: { kind: 'feat', featId: 'archivist' },
    canvas: '#1e1a17',
    surface: '#2f2822',
    frame: '#8a7550',
    accent: '#e0c98a',
    ink: '#f0e8db',
    material: MATERIALS.paper,
  },
  {
    id: 'sober-sky',
    name: 'Sober Sky',
    blurb: 'A hundred clean days, counted one at a time.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'clean-hundred' },
    canvas: '#101a24',
    surface: '#1a2a3a',
    frame: '#4a7a9a',
    accent: '#8fd8ff',
    ink: '#e2f0fa',
    good: '#3f9a8a',
    title: '#b8e8ff',
  },

  // --------------------------------------------------------- the long haul
  // These are the ones that cannot be bought. They only arrive by staying.
  {
    id: 'weathered',
    name: 'Weathered',
    blurb: 'A season in. The paint has started to settle.',
    rarity: 'rare',
    unlock: { kind: 'seniority', days: 90 },
    canvas: '#26201a',
    surface: '#3b3128',
    frame: '#7f6a4f',
    accent: '#e8c07a',
    ink: '#efe6d8',
    livingId: 'weathered',
  },
  {
    id: 'overgrown',
    name: 'Overgrown',
    blurb: 'Half a year. Something has taken root in the corners.',
    rarity: 'epic',
    unlock: { kind: 'seniority', days: 182 },
    canvas: '#1a2118',
    surface: '#2b3626',
    frame: '#5f7a4a',
    accent: '#a8d96a',
    ink: '#e6efdc',
    good: '#4a8f52',
    livingId: 'overgrown',
  },
  {
    id: 'heirloom',
    name: 'Heirloom',
    blurb: 'One year. The frame has cracked, and held.',
    rarity: 'legend',
    unlock: { kind: 'seniority', days: 365 },
    canvas: '#1f1a15',
    surface: '#332a20',
    frame: '#9a7f4f',
    accent: '#ffd98a',
    ink: '#f5ecd9',
    title: '#ffcf6a',
    livingId: 'heirloom',
  },
  {
    id: 'monument',
    name: 'Monument',
    blurb: 'Two years. Stone, moss, and the marks of weather.',
    rarity: 'legend',
    unlock: { kind: 'seniority', days: 730 },
    canvas: '#191b1a',
    surface: '#282d2b',
    frame: '#6a7a72',
    accent: '#bfd8c8',
    ink: '#e8eeea',
    good: '#4a8f6a',
    livingId: 'monument',
  },
];

export const SKINS: Skin[] = SPECS.map(buildSkin);

export const SKIN_BY_ID = new Map(SKINS.map(s => [s.id, s]));

export const DEFAULT_SKIN_ID = 'classic';

export const getSkin = (id: string | null | undefined): Skin =>
  (id && SKIN_BY_ID.get(id)) || SKIN_BY_ID.get(DEFAULT_SKIN_ID)!;

export const RARITY_ORDER: Record<string, number> = {
  common: 0, rare: 1, epic: 2, legend: 3,
};
