import { Skin } from '../types';
import { buildSkin, SkinSpec } from './skins';
import { FX, GLOW, MATERIALS } from './patina';
import { CLASSIC } from './theme';

/**
 * The skin catalogue.
 *
 * Ordered roughly by when you meet them. Levels are spaced against the
 * rebalanced XP curve (level 30 at about a year of steady play, 40 at two,
 * 59 at five), so there is always a next one visible without any of them
 * arriving so fast that it stops meaning anything.
 *
 * Three ways in, deliberately different in character:
 *   - LEVEL rewards accumulated effort, and is the steady drip.
 *   - FEAT rewards a specific story: the thing you dodged for half a year,
 *     the streak you rebuilt after a relapse.
 *   - SENIORITY rewards nothing but having stayed. It cannot be bought,
 *     rushed or farmed, only outlived — which is exactly why those skins are
 *     the ones that visibly age with the account.
 */

/**
 * The starting palette, reused verbatim by every seniority skin.
 *
 * Spread rather than referenced so those skins stay ordinary specs that the
 * builder and the contrast validator treat like any other.
 */
const TAVERN = {
  canvas: CLASSIC.canvas,
  surface: CLASSIC.surface,
  frame: CLASSIC.frame,
  accent: CLASSIC.accent,
  ink: CLASSIC.ink,
  tokens: { ...CLASSIC },
} as const;

const SPECS: SkinSpec[] = [
  // ---------------------------------------------------------------- default
  {
    id: 'classic',
    name: 'Tavern',
    blurb: 'Where it started. Oak, candlelight and a hard shadow.',
    rarity: 'common',
    unlock: { kind: 'default' },
    canvas: CLASSIC.canvas,
    surface: CLASSIC.surface,
    frame: CLASSIC.frame,
    accent: CLASSIC.accent,
    ink: CLASSIC.ink,
    tokens: { ...CLASSIC },
  },

  // ------------------------------------------------------- the early ladder
  {
    id: 'moss',
    name: 'Deep Moss',
    blurb: 'A forest floor after rain.',
    rarity: 'common',
    unlock: { kind: 'level', level: 3 },
    canvas: '#1b241d',
    surface: '#2e3d31',
    frame: '#5a7a5f',
    accent: '#9ed36f',
    ink: '#e4efdc',
    good: '#3f8f52',
    miss: '#8a5a24',
  },
  {
    id: 'dusk',
    name: 'Dusk Harbour',
    blurb: 'The blue hour, just before the lamps come on.',
    rarity: 'common',
    unlock: { kind: 'level', level: 5 },
    canvas: '#17202e',
    surface: '#243349',
    frame: '#4a6a94',
    accent: '#ffb35c',
    ink: '#e2ebf7',
    good: '#2f8a6b',
    miss: '#a05a2c',
    info: '#7fd4e8',
  },
  {
    id: 'ember',
    name: 'Ember',
    blurb: 'Banked coals that refuse to go out.',
    rarity: 'common',
    unlock: { kind: 'level', level: 8 },
    canvas: '#241416',
    surface: '#3a1f21',
    frame: '#8a4038',
    accent: '#ff8a4c',
    ink: '#f7e2da',
    good: '#4f8f5a',
    danger: '#b02a2a',
    material: { fx: FX.embers },
  },
  {
    id: 'slate',
    name: 'Slate',
    blurb: 'Quiet, grey, and impossible to argue with.',
    rarity: 'common',
    unlock: { kind: 'level', level: 11 },
    canvas: '#1c1e21',
    surface: '#2b2e33',
    frame: '#5a6069',
    accent: '#9fb4c9',
    ink: '#e6e9ed',
    good: '#4a8f6d',
    xp: '#b9a6e6',
    material: MATERIALS.stone,
  },
  {
    id: 'parchment',
    name: 'Parchment',
    blurb: 'Ink on old paper. The first light skin.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 14 },
    canvas: '#e8dfc8',
    surface: '#f3ecd9',
    frame: '#a08a5f',
    accent: '#9c5b1f',
    ink: '#3a2f22',
    good: '#3f6b35',
    miss: '#9a5a1e',
    danger: '#8f2a24',
    warn: '#8a5a12',
    xp: '#6a3fa0',
    info: '#1f6b7a',
    title: '#7a3f14',
    material: MATERIALS.paper,
  },
  {
    id: 'orchid',
    name: 'Orchid Court',
    blurb: 'Purple velvet and brass fittings.',
    rarity: 'common',
    unlock: { kind: 'level', level: 17 },
    canvas: '#1e1729',
    surface: '#2e2340',
    frame: '#6a4f9a',
    accent: '#e0b0ff',
    ink: '#ece3f7',
    good: '#3f8f78',
    xp: '#ffd6a5',
    material: MATERIALS.cloth,
  },
  {
    id: 'rust',
    name: 'Rust & Bone',
    blurb: 'Weathered iron. Still holding.',
    rarity: 'common',
    unlock: { kind: 'level', level: 20 },
    canvas: '#221c19',
    surface: '#382c26',
    frame: '#8a5a3a',
    accent: '#d9a066',
    ink: '#efe3d6',
    good: '#5a8a4a',
  },
  {
    id: 'tide',
    name: 'Tidepool',
    blurb: 'Cold water over green stone.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 24 },
    canvas: '#101f24',
    surface: '#1b3038',
    frame: '#3f6f7a',
    accent: '#6fe0c8',
    ink: '#dceff2',
    good: '#2f9a7a',
    miss: '#96622a',
    info: '#8fd8ff',
    material: { ...MATERIALS.glass, fx: FX.bubbles },
  },
  {
    id: 'sakura',
    name: 'Sakura Dusk',
    blurb: 'Petals against a darkening sky.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 28 },
    canvas: '#241a22',
    surface: '#3a2a33',
    frame: '#9a5f77',
    accent: '#ffa8c5',
    ink: '#f7e4ec',
    good: '#5a9a72',
    xp: '#c9a8ff',
    material: { ...MATERIALS.cloth, fx: FX.petals },
  },
  {
    id: 'gilded',
    name: 'Gilded',
    blurb: 'A year of showing up, in gold leaf.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 32 },
    canvas: '#191510',
    surface: '#2a2318',
    frame: '#b8912f',
    accent: '#ffd76a',
    ink: '#f7efd9',
    good: '#4f8f52',
    title: '#ffc94a',
    material: { ...MATERIALS.metal, fx: FX.sheen, glow: GLOW.gold },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    blurb: 'Volcanic glass. Nothing decorative left.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 40 },
    canvas: '#0d0d10',
    surface: '#191920',
    frame: '#3a3a48',
    accent: '#00e5b0',
    ink: '#e8e8f0',
    good: '#00b389',
    danger: '#e0344a',
    xp: '#9d7bff',
    info: '#4fd6ff',
    material: { ...MATERIALS.glass, fx: FX.roll },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    blurb: 'Two years of nights, and the sky finally answered.',
    rarity: 'legend',
    unlock: { kind: 'level', level: 50 },
    canvas: '#0b1220',
    surface: '#14203a',
    frame: '#3f6fa8',
    accent: '#7effc8',
    ink: '#e6f0ff',
    good: '#2fc79a',
    miss: '#b06a2a',
    xp: '#b48cff',
    info: '#6fe0ff',
    title: '#a8ffe0',
    material: { ...MATERIALS.crt, fx: FX.roll, glow: GLOW.mint },
  },


  // --------------------------------------------------- the wider level ladder
  // Filling in and extending the rungs. A ladder with gaps stops pulling, and
  // one that ends at level 50 stops pulling after two years.
  {
    id: 'candle',
    name: 'Candlelit',
    blurb: 'One small flame, and the rest of the room can wait.',
    rarity: 'common',
    unlock: { kind: 'level', level: 2 },
    canvas: '#1d1610',
    surface: '#2e2318',
    frame: '#7a5a33',
    accent: '#ffca70',
    ink: '#f4e6cf',
    good: '#5a8a48',
    title: '#ffb84a',
  },
  {
    id: 'abyss',
    name: 'Abyss',
    blurb: 'Deep water. Nothing up there is urgent.',
    rarity: 'common',
    unlock: { kind: 'level', level: 6 },
    canvas: '#08161c',
    surface: '#10262f',
    frame: '#2f5f6f',
    accent: '#54d5d5',
    ink: '#d8eef2',
    good: '#2f9a86',
    miss: '#a4622a',
    info: '#7fe0ff',
  },
  {
    id: 'vineyard',
    name: 'Vineyard',
    blurb: 'Wine-dark rows, cut at the end of the season.',
    rarity: 'common',
    unlock: { kind: 'level', level: 10 },
    canvas: '#1e1218',
    surface: '#301c26',
    frame: '#7a3f52',
    accent: '#e28aa0',
    ink: '#f2e0e6',
    good: '#5f8f52',
    xp: '#d9b3ff',
    material: MATERIALS.cloth,
  },
  {
    id: 'sandstone',
    name: 'Sandstone',
    blurb: 'Sun on a wall that has stood a long time.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 13 },
    canvas: '#ded1b6',
    surface: '#eee3cb',
    frame: '#9b8055',
    accent: '#a8531c',
    ink: '#372c1e',
    good: '#3d6631',
    miss: '#96551b',
    danger: '#8c2a20',
    warn: '#7f5410',
    xp: '#5f3a9a',
    info: '#1c6472',
    title: '#7d3d10',
    material: MATERIALS.stone,
  },
  {
    id: 'nocturne',
    name: 'Nocturne',
    blurb: 'The hours when nobody is asking anything of you.',
    rarity: 'common',
    unlock: { kind: 'level', level: 16 },
    canvas: '#141126',
    surface: '#211c3c',
    frame: '#4f4585',
    accent: '#9d8cff',
    ink: '#e6e2fa',
    good: '#3f8f78',
    xp: '#ffd6a5',
    info: '#7fc9ff',
  },
  {
    id: 'copper',
    name: 'Copper Works',
    blurb: 'Beaten metal going quietly green.',
    rarity: 'common',
    unlock: { kind: 'level', level: 19 },
    canvas: '#1c1815',
    surface: '#2d2620',
    frame: '#96603a',
    accent: '#e0965a',
    ink: '#f0e4d6',
    good: '#3f8f7a',
    info: '#6fd6c0',
    material: MATERIALS.metal,
  },
  {
    id: 'frost',
    name: 'Frostbite',
    blurb: 'Cold, bright and entirely awake.',
    rarity: 'common',
    unlock: { kind: 'level', level: 22 },
    canvas: '#0e1418',
    surface: '#1a242b',
    frame: '#4a6f82',
    accent: '#a8e4ff',
    ink: '#e8f4fa',
    good: '#3f9a8f',
    miss: '#a06430',
    material: { ...MATERIALS.glass, fx: FX.snow },
  },
  {
    id: 'terracotta',
    name: 'Red Clay',
    blurb: 'Fired clay, still warm from the kiln.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 26 },
    canvas: '#e3cdbb',
    surface: '#f2e2d4',
    frame: '#a2664a',
    accent: '#9c3f1f',
    ink: '#3a271e',
    good: '#3d6636',
    miss: '#8f4f18',
    danger: '#8f2a20',
    warn: '#7a5210',
    xp: '#5f3a9a',
    info: '#1c6472',
    title: '#8a3512',
  },
  {
    id: 'jade',
    name: 'Jade Court',
    blurb: 'Green stone and gold thread. A year of it.',
    rarity: 'rare',
    unlock: { kind: 'level', level: 30 },
    canvas: '#0f1c18',
    surface: '#1a2e28',
    frame: '#3f7a63',
    accent: '#ffd88a',
    ink: '#e2f0ea',
    good: '#3f9a72',
    title: '#ffc96a',
    material: MATERIALS.cloth,
  },
  {
    id: 'ashfall',
    name: 'Ashfall',
    blurb: 'Everything grey, and one thing still glowing.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 35 },
    canvas: '#191719',
    surface: '#2a262b',
    frame: '#5f5763',
    accent: '#ff8a5c',
    ink: '#eae6ec',
    good: '#5a8f6a',
    danger: '#c4392e',
    material: MATERIALS.stone,
  },
  {
    id: 'neon',
    name: 'Neon Alley',
    blurb: 'Rain on the tarmac and a sign that never sleeps.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 38 },
    canvas: '#0b0d16',
    surface: '#161a2c',
    frame: '#3f3f7a',
    accent: '#ff5cc8',
    ink: '#e8e8f8',
    good: '#28c7a0',
    miss: '#b0682a',
    xp: '#a88cff',
    info: '#4fe0ff',
    title: '#ff7ad6',
    material: { ...MATERIALS.crt, fx: FX.neon, glow: GLOW.pink },
  },
  {
    id: 'blackletter',
    name: 'Iron Gall',
    blurb: 'Bone paper, iron ink, nothing decorative.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 44 },
    canvas: '#e6e2d8',
    surface: '#f4f1e9',
    frame: '#5a5648',
    accent: '#8a2018',
    ink: '#22201c',
    good: '#2f5c30',
    miss: '#8a5310',
    danger: '#8a1f18',
    warn: '#6f5008',
    xp: '#4f2f8a',
    info: '#155e6b',
    title: '#7a1c14',
    material: MATERIALS.paper,
  },
  {
    id: 'solarflare',
    name: 'Solar Flare',
    blurb: 'Something enormous, a long way off, still burning.',
    rarity: 'epic',
    unlock: { kind: 'level', level: 47 },
    canvas: '#170f08',
    surface: '#2a1a0d',
    frame: '#a05a1a',
    accent: '#ffb02e',
    ink: '#fdecd4',
    good: '#5f9a45',
    danger: '#d4402a',
    title: '#ff8a1e',
    material: { ...MATERIALS.metal, fx: FX.embers, glow: GLOW.amber },
  },
  {
    id: 'nebula',
    name: 'Nebula',
    blurb: 'Dust that has been collapsing into light for a very long time.',
    rarity: 'legend',
    unlock: { kind: 'level', level: 55 },
    canvas: '#0c0818',
    surface: '#191030',
    frame: '#5a3f9a',
    accent: '#d7a8ff',
    ink: '#ece4fa',
    good: '#3fbf9a',
    miss: '#b06a3a',
    xp: '#8ce0ff',
    info: '#6fd8ff',
    title: '#ffb3f0',
    material: { ...MATERIALS.crt, fx: FX.stars, glow: GLOW.violet },
  },
  {
    id: 'eclipse',
    name: 'Eclipse',
    blurb: 'Total dark with a ring of fire around it.',
    rarity: 'legend',
    unlock: { kind: 'level', level: 60 },
    canvas: '#08080a',
    surface: '#141418',
    frame: '#4a4038',
    accent: '#ffcf5c',
    ink: '#eeeaf0',
    good: '#3f9a72',
    danger: '#d4382e',
    title: '#ffdf8a',
    material: { ...MATERIALS.glass, fx: FX.stars, glow: GLOW.gold },
  },
  {
    id: 'ascendant',
    name: 'Ascendant',
    blurb: 'Five years. There is no higher rung to draw.',
    rarity: 'legend',
    unlock: { kind: 'level', level: 70 },
    canvas: '#0d1014',
    surface: '#181e26',
    frame: '#8a7f5a',
    accent: '#f0e6c0',
    ink: '#f4f6fa',
    good: '#4fb08a',
    xp: '#c9b3ff',
    info: '#8fd8ff',
    title: '#ffeeb8',
    material: { ...MATERIALS.metal, fx: FX.motes, glow: GLOW.gold },
  },

  // -------------------------------------------------------------- the feats
  {
    id: 'first-light',
    name: 'First Light',
    blurb: 'For the very first thing you ticked off.',
    rarity: 'common',
    unlock: { kind: 'feat', featId: 'first-blood' },
    canvas: '#20191f',
    surface: '#332633',
    frame: '#7a5a7a',
    accent: '#ffc9a8',
    ink: '#f2e6ee',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    blurb: 'A hundred days on one habit. Bronze and blood.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'century' },
    canvas: '#1d1613',
    surface: '#31241d',
    frame: '#a86f3a',
    accent: '#ff9f45',
    ink: '#f5e6d5',
    good: '#5f8f45',
    danger: '#a82e26',
    title: '#ffb45c',
  },
  {
    id: 'excavator',
    name: 'Excavator',
    blurb: 'You dug out something buried for half a year.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'excavation' },
    canvas: '#1a1a14',
    surface: '#2b2b1f',
    frame: '#7a7a4a',
    accent: '#d9d96a',
    ink: '#eeeedd',
    good: '#6a9a4a',
    miss: '#8a6a2a',
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    blurb: 'You slipped, and built it back higher.',
    rarity: 'legend',
    unlock: { kind: 'feat', featId: 'phoenix' },
    canvas: '#1c1013',
    surface: '#331a1c',
    frame: '#b04a3a',
    accent: '#ffb347',
    ink: '#ffeadf',
    good: '#5f9a5a',
    danger: '#d4402e',
    title: '#ff7a3c',
    material: { fx: FX.embers, glow: GLOW.amber },
  },
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    blurb: 'An empty board. Rarer than any streak.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'clean-slate' },
    canvas: '#f2f2ef',
    surface: '#ffffff',
    frame: '#8f9a96',
    accent: '#1f7a68',
    ink: '#22282a',
    good: '#2f7a4f',
    miss: '#9a5a1e',
    danger: '#8f2a24',
    warn: '#8a5a12',
    xp: '#5a3fa0',
    info: '#1f6b8a',
    title: '#1f7a68',
  },
  {
    id: 'ironclad',
    name: 'Ironclad',
    blurb: 'A month without a single miss.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'unbroken-month' },
    canvas: '#15181c',
    surface: '#222830',
    frame: '#5f7285',
    accent: '#c8d8e8',
    ink: '#eef3f8',
    good: '#3f8f7a',
    xp: '#a8b8ff',
    material: MATERIALS.metal,
  },
  {
    id: 'archivist',
    name: 'Archivist',
    blurb: 'Ten long-buried jobs, all finished.',
    rarity: 'rare',
    unlock: { kind: 'feat', featId: 'archivist' },
    canvas: '#1e1a17',
    surface: '#2f2822',
    frame: '#8a7550',
    accent: '#e0c98a',
    ink: '#f0e8db',
    material: MATERIALS.paper,
  },
  {
    id: 'sober-sky',
    name: 'Sober Sky',
    blurb: 'A hundred clean days, counted one at a time.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'clean-hundred' },
    canvas: '#101a24',
    surface: '#1a2a3a',
    frame: '#4a7a9a',
    accent: '#8fd8ff',
    ink: '#e2f0fa',
    good: '#3f9a8a',
    title: '#b8e8ff',
    material: { fx: FX.stars },
  },

  {
    id: 'flawless',
    name: 'Flawless',
    blurb: 'Seven days where nothing slipped through.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'perfect-week' },
    canvas: '#0f1a16',
    surface: '#1a2a24',
    frame: '#3f7a5f',
    accent: '#8fffc8',
    ink: '#e2f4ec',
    good: '#2fa87a',
    title: '#a8ffd8',
    material: { ...MATERIALS.glass, glow: GLOW.mint },
  },
  {
    id: 'ironwill',
    name: 'Iron Will',
    blurb: 'Fifty urges, ridden out one breath at a time.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'iron-will' },
    canvas: '#141518',
    surface: '#212429',
    frame: '#5f6672',
    accent: '#c8d4e0',
    ink: '#eceff3',
    good: '#4a8f72',
    danger: '#c4382e',
    material: MATERIALS.metal,
  },
  {
    id: 'triage',
    name: 'Triage',
    blurb: 'Five things cleared before lunch.',
    rarity: 'rare',
    unlock: { kind: 'feat', featId: 'triage' },
    canvas: '#191410',
    surface: '#2a221a',
    frame: '#8a6a3a',
    accent: '#ffd07a',
    ink: '#f2e8d8',
    good: '#5a9a4a',
    miss: '#a86a2a',
  },
  {
    id: 'chronicle',
    name: 'The Chronicle',
    blurb: 'Sixty days written down. The record is yours.',
    rarity: 'epic',
    unlock: { kind: 'feat', featId: 'chronicler' },
    canvas: '#e4dcc8',
    surface: '#f2ecdc',
    frame: '#8a7048',
    accent: '#7a4a1c',
    ink: '#312a1e',
    good: '#3a6230',
    miss: '#8f5518',
    danger: '#8a281f',
    warn: '#755008',
    xp: '#553296',
    info: '#175f6e',
    title: '#6b3a12',
    material: MATERIALS.paper,
  },

  // --------------------------------------------------------- the long haul
  // These cannot be bought. They only arrive by staying — and they are all the
  // SAME room, the one you started in, at six different ages. Nothing here
  // changes a single colour: the tavern is exactly the tavern, and what you get
  // for the years is the moss on the sill and the crack across the frame.
  // Giving each its own palette, which is what this used to do, turned one
  // story about staying into six unrelated paint jobs.
  {
    id: 'sapling',
    name: 'Sapling',
    blurb: 'A month in. Something green has come up by the door.',
    rarity: 'common',
    unlock: { kind: 'seniority', days: 30 },
    ...TAVERN,
    patina: { plants: 0.2 },
  },
  {
    id: 'weathered',
    name: 'Weathered',
    blurb: 'A season. The paint has started to craze.',
    rarity: 'rare',
    unlock: { kind: 'seniority', days: 90 },
    ...TAVERN,
    patina: { plants: 0.34, cracks: 0.32, varnish: 0.12 },
  },
  {
    id: 'overgrown',
    name: 'Overgrown',
    blurb: 'Half a year, and the garden has stopped asking permission.',
    rarity: 'epic',
    unlock: { kind: 'seniority', days: 182 },
    ...TAVERN,
    patina: { plants: 0.78, cracks: 0.4, varnish: 0.15 },
  },
  {
    id: 'heirloom',
    name: 'Heirloom',
    blurb: 'A year. Cracked, darkened, and clearly looked after.',
    rarity: 'legend',
    unlock: { kind: 'seniority', days: 365 },
    ...TAVERN,
    patina: { plants: 0.5, cracks: 0.62, varnish: 0.8, dust: 0.25 },
  },
  {
    id: 'monument',
    name: 'Monument',
    blurb: 'Two years. Still standing, and the weather knows it.',
    rarity: 'legend',
    unlock: { kind: 'seniority', days: 730 },
    ...TAVERN,
    patina: { plants: 0.88, cracks: 0.92, varnish: 0.35, dust: 0.35 },
  },
  {
    id: 'cathedral',
    name: 'Cathedral',
    blurb: 'Three years. Dust in the light, and nobody left who built it.',
    rarity: 'legend',
    unlock: { kind: 'seniority', days: 1095 },
    ...TAVERN,
    patina: { plants: 1, cracks: 1, varnish: 0.6, dust: 0.8 },
  },
];

export const SKINS: Skin[] = SPECS.map(buildSkin);

export const SKIN_BY_ID = new Map(SKINS.map(s => [s.id, s]));

export const DEFAULT_SKIN_ID = 'classic';

export const getSkin = (id: string | null | undefined): Skin =>
  (id && SKIN_BY_ID.get(id)) || SKIN_BY_ID.get(DEFAULT_SKIN_ID)!;

export const RARITY_ORDER: Record<string, number> = {
  common: 0, rare: 1, epic: 2, legend: 3,
};
